/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DuelistKingDistributorInterface extends ethers.utils.Interface {
  functions: {
    "compute(bytes)": FunctionFragment;
    "getCampaign(uint256)": FunctionFragment;
    "getCampaignIndex()": FunctionFragment;
    "getCard(uint256)": FunctionFragment;
    "getCardIndex()": FunctionFragment;
    "getDomain()": FunctionFragment;
    "getRegistry()": FunctionFragment;
    "issueCard(string,string)": FunctionFragment;
    "issueGenesisEdittion(uint256,address)": FunctionFragment;
    "newCampaign(tuple)": FunctionFragment;
    "openBox(uint256,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "compute", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCardIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getDomain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issueCard",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueGenesisEdittion",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "newCampaign",
    values: [
      {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openBox",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "compute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCardIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDomain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueGenesisEdittion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openBox", data: BytesLike): Result;

  events: {
    "NewCampaign(uint256,uint256,uint64)": EventFragment;
    "NewCard(uint256,address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewCampaign"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCard"): EventFragment;
}

export class DuelistKingDistributor extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: DuelistKingDistributorInterface;

  functions: {
    compute(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "compute(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getCampaign(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[]
        ] & {
          opened: BigNumber;
          softCap: BigNumber;
          deadline: BigNumber;
          generation: BigNumber;
          start: BigNumber;
          end: BigNumber;
          designs: BigNumber;
          distribution: BigNumber[];
        }
      ]
    >;

    "getCampaign(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[]
        ] & {
          opened: BigNumber;
          softCap: BigNumber;
          deadline: BigNumber;
          generation: BigNumber;
          start: BigNumber;
          end: BigNumber;
          designs: BigNumber;
          distribution: BigNumber[];
        }
      ]
    >;

    getCampaignIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getCampaignIndex()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCard(index: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "getCard(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCardIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getCardIndex()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDomain(overrides?: CallOverrides): Promise<[string]>;

    "getDomain()"(overrides?: CallOverrides): Promise<[string]>;

    getRegistry(overrides?: CallOverrides): Promise<[string]>;

    "getRegistry()"(overrides?: CallOverrides): Promise<[string]>;

    issueCard(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "issueCard(string,string)"(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    issueGenesisEdittion(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "issueGenesisEdittion(uint256,address)"(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    newCampaign(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "newCampaign((uint64,uint64,uint64,uint64,uint64,uint64,uint64,uint256[]))"(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    openBox(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "openBox(uint256,address,uint256)"(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  compute(data: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  "compute(bytes)"(
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getCampaign(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber[]
    ] & {
      opened: BigNumber;
      softCap: BigNumber;
      deadline: BigNumber;
      generation: BigNumber;
      start: BigNumber;
      end: BigNumber;
      designs: BigNumber;
      distribution: BigNumber[];
    }
  >;

  "getCampaign(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber[]
    ] & {
      opened: BigNumber;
      softCap: BigNumber;
      deadline: BigNumber;
      generation: BigNumber;
      start: BigNumber;
      end: BigNumber;
      designs: BigNumber;
      distribution: BigNumber[];
    }
  >;

  getCampaignIndex(overrides?: CallOverrides): Promise<BigNumber>;

  "getCampaignIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCard(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getCard(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getCardIndex(overrides?: CallOverrides): Promise<BigNumber>;

  "getCardIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

  getDomain(overrides?: CallOverrides): Promise<string>;

  "getDomain()"(overrides?: CallOverrides): Promise<string>;

  getRegistry(overrides?: CallOverrides): Promise<string>;

  "getRegistry()"(overrides?: CallOverrides): Promise<string>;

  issueCard(
    name: string,
    symbol: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "issueCard(string,string)"(
    name: string,
    symbol: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  issueGenesisEdittion(
    cardId: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "issueGenesisEdittion(uint256,address)"(
    cardId: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  newCampaign(
    campaign: {
      opened: BigNumberish;
      softCap: BigNumberish;
      deadline: BigNumberish;
      generation: BigNumberish;
      start: BigNumberish;
      end: BigNumberish;
      designs: BigNumberish;
      distribution: BigNumberish[];
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "newCampaign((uint64,uint64,uint64,uint64,uint64,uint64,uint64,uint256[]))"(
    campaign: {
      opened: BigNumberish;
      softCap: BigNumberish;
      deadline: BigNumberish;
      generation: BigNumberish;
      start: BigNumberish;
      end: BigNumberish;
      designs: BigNumberish;
      distribution: BigNumberish[];
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  openBox(
    campaignId: BigNumberish,
    buyer: string,
    numberOfBoxes: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "openBox(uint256,address,uint256)"(
    campaignId: BigNumberish,
    buyer: string,
    numberOfBoxes: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    compute(data: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "compute(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getCampaign(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[]
      ] & {
        opened: BigNumber;
        softCap: BigNumber;
        deadline: BigNumber;
        generation: BigNumber;
        start: BigNumber;
        end: BigNumber;
        designs: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getCampaign(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[]
      ] & {
        opened: BigNumber;
        softCap: BigNumber;
        deadline: BigNumber;
        generation: BigNumber;
        start: BigNumber;
        end: BigNumber;
        designs: BigNumber;
        distribution: BigNumber[];
      }
    >;

    getCampaignIndex(overrides?: CallOverrides): Promise<BigNumber>;

    "getCampaignIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCard(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getCard(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getCardIndex(overrides?: CallOverrides): Promise<BigNumber>;

    "getCardIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDomain(overrides?: CallOverrides): Promise<string>;

    "getDomain()"(overrides?: CallOverrides): Promise<string>;

    getRegistry(overrides?: CallOverrides): Promise<string>;

    "getRegistry()"(overrides?: CallOverrides): Promise<string>;

    issueCard(
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "issueCard(string,string)"(
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    issueGenesisEdittion(
      cardId: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "issueGenesisEdittion(uint256,address)"(
      cardId: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    newCampaign(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "newCampaign((uint64,uint64,uint64,uint64,uint64,uint64,uint64,uint256[]))"(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openBox(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "openBox(uint256,address,uint256)"(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    NewCampaign(
      campaginId: BigNumberish | null,
      generation: BigNumberish | null,
      designs: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { campaginId: BigNumber; generation: BigNumber; designs: BigNumber }
    >;

    NewCard(
      cardIndex: BigNumberish | null,
      cardAddress: string | null,
      cardName: string | null
    ): TypedEventFilter<
      [BigNumber, string, string],
      { cardIndex: BigNumber; cardAddress: string; cardName: string }
    >;
  };

  estimateGas: {
    compute(data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "compute(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getCampaign(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCampaign(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCampaignIndex(overrides?: CallOverrides): Promise<BigNumber>;

    "getCampaignIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCard(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "getCard(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCardIndex(overrides?: CallOverrides): Promise<BigNumber>;

    "getCardIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDomain(overrides?: CallOverrides): Promise<BigNumber>;

    "getDomain()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    "getRegistry()"(overrides?: CallOverrides): Promise<BigNumber>;

    issueCard(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "issueCard(string,string)"(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    issueGenesisEdittion(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "issueGenesisEdittion(uint256,address)"(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    newCampaign(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "newCampaign((uint64,uint64,uint64,uint64,uint64,uint64,uint64,uint256[]))"(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    openBox(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "openBox(uint256,address,uint256)"(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    compute(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "compute(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getCampaign(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCampaign(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCampaignIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCampaignIndex()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCard(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCard(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCardIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCardIndex()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDomain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDomain()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getRegistry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    issueCard(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "issueCard(string,string)"(
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    issueGenesisEdittion(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "issueGenesisEdittion(uint256,address)"(
      cardId: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    newCampaign(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "newCampaign((uint64,uint64,uint64,uint64,uint64,uint64,uint64,uint256[]))"(
      campaign: {
        opened: BigNumberish;
        softCap: BigNumberish;
        deadline: BigNumberish;
        generation: BigNumberish;
        start: BigNumberish;
        end: BigNumberish;
        designs: BigNumberish;
        distribution: BigNumberish[];
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    openBox(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "openBox(uint256,address,uint256)"(
      campaignId: BigNumberish,
      buyer: string,
      numberOfBoxes: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
