/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from './ERC20';
export type { DuelistKingDistributor } from './DuelistKingDistributor';
export type { RNG } from './RNG';
export type { NFT } from './NFT';
export type { Registry } from './Registry';
export type { OracleProxy } from './OracleProxy';
