/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface OracleProxyInterface extends ethers.utils.Interface {
  functions: {
    "addController(address)": FunctionFragment;
    "getDomain()": FunctionFragment;
    "getRegistry()": FunctionFragment;
    "getValidTimeNonce(uint256,uint256)": FunctionFragment;
    "isController(address)": FunctionFragment;
    "removeController(address)": FunctionFragment;
    "safeCall(bytes,address,uint256,bytes)": FunctionFragment;
    "safeDelegateCall(bytes,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addController",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getDomain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidTimeNonce",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeCall",
    values: [BytesLike, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeDelegateCall",
    values: [BytesLike, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDomain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidTimeNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeDelegateCall",
    data: BytesLike
  ): Result;

  events: {
    "DelistAddress(address)": EventFragment;
    "ListAddress(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelistAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListAddress"): EventFragment;
}

export class OracleProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: OracleProxyInterface;

  functions: {
    addController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getDomain(overrides?: CallOverrides): Promise<[string]>;

    "getDomain()"(overrides?: CallOverrides): Promise<[string]>;

    getRegistry(overrides?: CallOverrides): Promise<[string]>;

    "getRegistry()"(overrides?: CallOverrides): Promise<[string]>;

    getValidTimeNonce(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getValidTimeNonce(uint256,uint256)"(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isController(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isController(address)"(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    safeCall(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeCall(bytes,address,uint256,bytes)"(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    safeDelegateCall(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeDelegateCall(bytes,address,bytes)"(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addController(
    controllerAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addController(address)"(
    controllerAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getDomain(overrides?: CallOverrides): Promise<string>;

  "getDomain()"(overrides?: CallOverrides): Promise<string>;

  getRegistry(overrides?: CallOverrides): Promise<string>;

  "getRegistry()"(overrides?: CallOverrides): Promise<string>;

  getValidTimeNonce(
    timeout: BigNumberish,
    randomNonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getValidTimeNonce(uint256,uint256)"(
    timeout: BigNumberish,
    randomNonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isController(
    inputAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isController(address)"(
    inputAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeController(
    controllerAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeController(address)"(
    controllerAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  safeCall(
    proof: BytesLike,
    target: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeCall(bytes,address,uint256,bytes)"(
    proof: BytesLike,
    target: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  safeDelegateCall(
    proof: BytesLike,
    target: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeDelegateCall(bytes,address,bytes)"(
    proof: BytesLike,
    target: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addController(
      controllerAddr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "addController(address)"(
      controllerAddr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getDomain(overrides?: CallOverrides): Promise<string>;

    "getDomain()"(overrides?: CallOverrides): Promise<string>;

    getRegistry(overrides?: CallOverrides): Promise<string>;

    "getRegistry()"(overrides?: CallOverrides): Promise<string>;

    getValidTimeNonce(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getValidTimeNonce(uint256,uint256)"(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isController(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isController(address)"(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeController(
      controllerAddr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "removeController(address)"(
      controllerAddr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    safeCall(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "safeCall(bytes,address,uint256,bytes)"(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    safeDelegateCall(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "safeDelegateCall(bytes,address,bytes)"(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    DelistAddress(
      addr: string | null
    ): TypedEventFilter<[string], { addr: string }>;

    ListAddress(
      addr: string | null
    ): TypedEventFilter<[string], { addr: string }>;
  };

  estimateGas: {
    addController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getDomain(overrides?: CallOverrides): Promise<BigNumber>;

    "getDomain()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    "getRegistry()"(overrides?: CallOverrides): Promise<BigNumber>;

    getValidTimeNonce(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getValidTimeNonce(uint256,uint256)"(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isController(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isController(address)"(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    safeCall(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeCall(bytes,address,uint256,bytes)"(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    safeDelegateCall(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeDelegateCall(bytes,address,bytes)"(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getDomain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDomain()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getRegistry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getValidTimeNonce(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getValidTimeNonce(uint256,uint256)"(
      timeout: BigNumberish,
      randomNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isController(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isController(address)"(
      inputAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeController(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeController(address)"(
      controllerAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    safeCall(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeCall(bytes,address,uint256,bytes)"(
      proof: BytesLike,
      target: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    safeDelegateCall(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeDelegateCall(bytes,address,bytes)"(
      proof: BytesLike,
      target: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
